import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";
import StoreProvider from "@/components/StoreProvider";
import TopNavBar from "@/components/TopNavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <StoreProvider>
      <body className={`${inter.className} `}>
        

       
      <main >
        <TopNavBar/>
        
        <div className="flex justify-between items-start">
          <Sidebar/>
          <div className="w-full h-full">            
            <Toaster position="bottom-center"reverseOrder={false}/>
            {children }

          </div>
          </div>
      </main>
      </body>
    </StoreProvider>
  </html>
  );
}
